import type { Car, MarketplaceStats } from "./models";

export const fallbackCars: Car[] = [
  {
    id: 1,
    make: "Mercedes",
    model: "S-Class",
    year: 2024,
    price: 148000,
    monthlyInstallment: 2790,
    type: "sell",
    mileage: 8200,
    fuelType: "Petrol",
    transmission: "Automatic",
    imageUrl: "/hero-car.png",
    bodyType: "Sedan",
    isFeatured: true,
    description:
      "Executive luxury sedan with advanced comfort, driver assistance, and immaculate Gulf-market service history.",
  },
  {
    id: 2,
    make: "BMW",
    model: "X7",
    year: 2023,
    price: 119000,
    monthlyInstallment: 2240,
    type: "sell",
    mileage: 18500,
    fuelType: "Petrol",
    transmission: "Automatic",
    imageUrl: "/hero-car.png",
    bodyType: "SUV",
    isFeatured: true,
    description:
      "Seven-seat premium SUV with panoramic roof, executive package, and flexible financing available.",
  },
  {
    id: 3,
    make: "Audi",
    model: "A8",
    year: 2022,
    price: 89000,
    monthlyInstallment: 1690,
    type: "sell",
    mileage: 25500,
    fuelType: "Hybrid",
    transmission: "Automatic",
    imageUrl: "/hero-car.png",
    bodyType: "Sedan",
    isFeatured: true,
    description: "Quiet, refined flagship sedan with premium cabin technology and verified inspection.",
  },
  {
    id: 4,
    make: "Land Rover",
    model: "Range Rover Sport",
    year: 2024,
    price: 450,
    type: "rent",
    mileage: 9200,
    fuelType: "Petrol",
    transmission: "Automatic",
    imageUrl: "/hero-car.png",
    bodyType: "SUV",
    isFeatured: true,
    description: "Premium rental SUV available daily, weekly, or monthly with delivery across Dubai.",
  },
  {
    id: 5,
    make: "Lexus",
    model: "LX 600",
    year: 2023,
    price: 132000,
    monthlyInstallment: 2490,
    type: "sell",
    mileage: 17000,
    fuelType: "Petrol",
    transmission: "Automatic",
    imageUrl: "/hero-car.png",
    bodyType: "SUV",
    isFeatured: true,
    description: "Luxury SUV with commanding road presence, low mileage, and premium warranty options.",
  },
  {
    id: 6,
    make: "Porsche",
    model: "Cayenne",
    year: 2022,
    price: 98000,
    monthlyInstallment: 1880,
    type: "sell",
    mileage: 24000,
    fuelType: "Petrol",
    transmission: "Automatic",
    imageUrl: "/hero-car.png",
    bodyType: "SUV",
    isFeatured: false,
    description: "Performance-focused premium SUV with sport chrono package and full inspection report.",
  },
];

export const fallbackStats: MarketplaceStats = {
  totalCars: 15,
  carsForSale: 13,
  carsForRent: 2,
  totalMakes: 8,
  avgPrice: 95000,
  happyCustomers: 1240,
};
