// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/refinements/EditorialDepth.tsx": () => import("../components/mockups/refinements/EditorialDepth.tsx"),
  "./components/mockups/refinements/TightPremium.tsx": () => import("../components/mockups/refinements/TightPremium.tsx"),
  "./components/mockups/home-layouts/Editorial.tsx": () => import("../components/mockups/home-layouts/Editorial.tsx"),
  "./components/mockups/home-layouts/SearchFirst.tsx": () => import("../components/mockups/home-layouts/SearchFirst.tsx"),
  "./components/mockups/home-layouts/SplitPanel.tsx": () => import("../components/mockups/home-layouts/SplitPanel.tsx"),
  "./components/mockups/surprise/SurpriseCollection.tsx": () => import("../components/mockups/surprise/SurpriseCollection.tsx"),
  "./components/mockups/surprise/SurpriseDiscovery.tsx": () => import("../components/mockups/surprise/SurpriseDiscovery.tsx"),
  "./components/mockups/surprise/SurpriseIntent.tsx": () => import("../components/mockups/surprise/SurpriseIntent.tsx")
};
